function hard = getHard(x)
    hard =  ((1+1j)  * and((real(x)>=0),(imag(x)>=0)) + ...
            (1-1j)  * and((real(x)>=0),(imag(x)<0)) + ...
            (-1+1j) * and((real(x)<0),(imag(x)>=0)) + ...
            (-1-1j) * and((real(x)<0),(imag(x)<0))) / sqrt(2);
end